### ISSUE TITLE
您好，请问下flutter生成的Android目录里没有jniLibs、libs目录，直接手动创建一个么？

### ISSUE THREAD

**Issue by djytwy** [elo5/xfspeech_plugin#1]
如标题

**Comment by elo5** [comment]
是的，安卓在  1 android/ 下创建 libs目录，放入Msc.jar， 2 androd/src/main/ 下创建jniLibs目录，将 arm64-xxx 拷贝进这个目录
ios   在 ios目录下创建Frameworks目录，讲iflyMSC.framework拷贝进这个目录

**Comment by djytwy** [comment]
flutter生成的Android工程里面只有android/app/src/main,没有android/src/main的路径，请问下是在这个路径中添加arm64-xxx 这个目录么？我这样添加进来了，但白字里报错“/system/lib]]] couldn't find "libmsc.so"”

**Comment by elo5** [comment]
这个不是flutter create project, 这个是创建的plugin，里面的example文件夹才是类似于flutter create project的工程

需要添加的是在plugin工程的android目录（跟example目录同一级）

可以看这个链接了解plugin
https://flutter.dev/docs/development/packages-and-plugins/developing-packages

**Comment by elo5** [comment]
不是example文件夹里面的android文件夹

**Comment by djytwy** [comment]
嗯嗯，谢谢呀

**Comment by elo5** [comment]
不客气:)
